package com.marksy.os.gateway

import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.security.Key
import java.security.KeyStore
import java.security.KeyStoreSpi
import java.security.Provider
import java.util.Collections
import javax.crypto.SecretKey
import javax.crypto.spec.SecretKeySpec

/**
 * Test implementation of Android Keystore provider for unit tests.
 * Provides an in-memory KeyStore that mimics the behavior of Android's hardware-backed keystore
 * for testing purposes without requiring a real device.
 */
class TestAndroidKeyStoreProvider : Provider("AndroidKeyStore", 1.0, "Test Android Keystore Provider") {
    init {
        put("KeyStore.AndroidKeyStore", "com.marksy.os.gateway.TestAndroidKeyStoreSpi")
        put("KeyGenerator.AES", "com.marksy.os.gateway.TestAndroidKeyGenerator")
    }
}

/**
 * SPI (Service Provider Interface) implementation for the test Android KeyStore.
 * Stores keys in memory and allows encryption/decryption operations for testing.
 */
class TestAndroidKeyStoreSpi : KeyStoreSpi() {
    private val keys = mutableMapOf<String, Key>()
    private var isLoaded = false

    @Throws(IOException::class)
    override fun engineLoad(stream: InputStream?, password: CharArray?) {
        isLoaded = true
        // Also load from the TestAndroidKeyGenerator's shared storage
        keys.clear()
        keys.putAll(TestAndroidKeyGenerator.generatedKeys)
    }

    @Throws(IOException::class)
    override fun engineStore(stream: OutputStream?, password: CharArray?) {
    }

    override fun engineGetKey(alias: String?, password: CharArray?): Key? =
        if (alias != null) keys[alias] else null

    override fun engineGetCertificateChain(alias: String?): Array<java.security.cert.Certificate>? = null

    override fun engineGetCertificate(alias: String?): java.security.cert.Certificate? = null

    override fun engineGetCreationDate(alias: String?) = null

    override fun engineDeleteEntry(alias: String?) {
        keys.remove(alias)
    }

    override fun engineAliases(): java.util.Enumeration<String> =
        Collections.enumeration(keys.keys)

    override fun engineContainsAlias(alias: String?): Boolean =
        keys.containsKey(alias)

    override fun engineSize(): Int = keys.size

    override fun engineIsKeyEntry(alias: String?): Boolean =
        alias?.let { keys[it] is Key } ?: false

    override fun engineIsCertificateEntry(alias: String?): Boolean = false

    override fun engineGetCertificateAlias(cert: java.security.cert.Certificate?): String? = null

    override fun engineSetKeyEntry(
        alias: String?,
        key: Key?,
        password: CharArray?,
        chain: Array<java.security.cert.Certificate>?
    ) {
        if (alias != null && key != null) {
            keys[alias] = key
        }
    }

    override fun engineSetKeyEntry(alias: String?, key: ByteArray?, chain: Array<java.security.cert.Certificate>?) {
    }

    override fun engineSetCertificateEntry(alias: String?, cert: java.security.cert.Certificate?) {
    }
}

/**
 * Test implementation of KeyGenerator for AES in Android Keystore.
 * Generates AES keys that can be used with GCM mode for testing.
 */
class TestAndroidKeyGenerator : javax.crypto.KeyGeneratorSpi() {
    private var keySize = 256
    private var alias: String? = null

    companion object {
        // Shared storage for keys generated by this provider
        val generatedKeys = mutableMapOf<String, Key>()

        fun storeKey(alias: String, key: SecretKey) {
            generatedKeys[alias] = key
        }
    }

    override fun engineInit(random: java.security.SecureRandom?) {
        // Default initialization - use 256-bit key
        keySize = 256
    }

    override fun engineInit(keysize: Int, random: java.security.SecureRandom?) {
        this.keySize = keysize
    }

    override fun engineInit(params: java.security.spec.AlgorithmParameterSpec?, random: java.security.SecureRandom?) {
        if (params is android.security.keystore.KeyGenParameterSpec) {
            alias = params.keystoreAlias
            // Try to get key size from the parameter spec
            try {
                val keySizesField = params.javaClass.getDeclaredField("mKeySizes")
                keySizesField.isAccessible = true
                val keySizes = keySizesField.get(params) as? IntArray
                keySize = keySizes?.firstOrNull() ?: 256
            } catch (e: Exception) {
                keySize = 256
            }
        }
    }

    override fun engineGenerateKey(): SecretKey {
        // Generate a simple AES key for testing using standard Java crypto
        val bytes = ByteArray(keySize / 8)
        java.security.SecureRandom().nextBytes(bytes)
        val key = SecretKeySpec(bytes, 0, bytes.size, "AES")

        // Store in our shared storage if alias is set
        if (alias != null) {
            storeKey(alias!!, key)
        }

        return key
    }
}
